name: build and test crow dev

on:
  push:
    branches: [ dev ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install Visual Studio 2019 Build Tools
      uses: microsoft/setup-msbuild@v1.0.2
      id: setup_msbuild
    
    - name: Restore NuGet packages
      id: restore_nuget
      working-directory: ./crow
      run: nuget restore crow.sln

    - name: Installing vcpkg (windows)
      run: |
        cd ..
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat
        .\vcpkg.exe install curl:x64-windows
        .\vcpkg.exe integrate install
    
    - name: Setup VSTest and add to PATH
      uses: darenm/Setup-VSTest@v1
      id: setup_vstest
    
    - name: Run MSBuild
      id: run_msbuild
      working-directory: ./crow
      run: msbuild crow.sln
      env:
          USERNAME: ${{ secrets.USRNM }}
          PASSWORD: ${{ secrets.PSSWD }}
      
    - name: Run VSTest
      id: run_vstest
      working-directory: ./crow
      run: vstest.console.exe /Platform:x64 /Settings:best.runsettings D:\a\STIN\STIN\crow\x64\Debug\crowTest.dll

    - name: Setup .NET Core # Required to execute ReportGenerator
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x
        dotnet-quality: 'ga'

    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.1.20
      with:
        reports: D:\a\STIN\STIN\crow\TestResults\**\testResult.cobertura.xml
        targetdir: coveragereport
        
    - uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: coveragereport
