name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "raven-banking" #Must be unique in Heroku
          heroku_email: "peter.spurny@tul.cz"
          appdir: "crow"
          docker_build_args: |
            USRNM
            PSSWD
          env:
            NODE_ENV: ${{ secrets.USRNM }}
            SECRET_KEY: ${{ secrets.PSSWD }}