name: deploy crow

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install Visual Studio 2019 Build Tools
      uses: microsoft/setup-msbuild@v1.0.2
      id: setup_msbuild
    
    - name: Restore NuGet packages
      id: restore_nuget
      working-directory: ./crow
      run: nuget restore crow.sln

    - name: Installing vcpkg (windows)
      run: |
        cd ..
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat
        .\vcpkg.exe install curl:x64-windows
        .\vcpkg.exe integrate install
    
    - name: Setup VSTest and add to PATH
      uses: darenm/Setup-VSTest@v1
      id: setup_vstest
    
    - name: Run MSBuild
      id: run_msbuild
      working-directory: ./crow
      run: msbuild crow.sln
      
    - name: Run VSTest
      id: run_vstest
      working-directory: ./crow
      run: vstest.console.exe /Platform:x64 /Settings:best.runsettings D:\a\STIN\STIN\crow\x64\Debug\crowTest.dll
