name: C++ Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Visual Studio 2019 Build Tools
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: run-vcpkg
      uses: lukka/run-vcpkg@v11.1
    
    - name: Install Boost C++ Libraries
      run: |
        vcpkg install boost:x64-windows

