name: C++ Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Visual Studio 2019 Build Tools
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Install Boost C++ Libraries
      run: |
        choco install boost-msvc-14.2
        setx /M BOOST_ROOT "C:\local\boost_1_76_0"
