name: C++ Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Visual Studio 2019 Build Tools
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Install vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat
        setx /M VCPKG_ROOT "$(pwd)"
        setx /M PATH "%PATH%;$(pwd)\installed\x64-windows\bin"
        
    - name: Install Boost C++ Libraries
      run: |
        vcpkg install boost:x64-windows
        setx /M BOOST_ROOT "$(vcpkg --triplet x64-windows --print-root)/installed/x64-windows"
        
    - name: Install CURL Library
      run: |
        vcpkg install curl:x64-windows
        setx /M CURL_DIR "$(vcpkg --triplet x64-windows --print-root)/installed/x64-windows"

    - name: Build solution
      run: |
        msbuild crow.sln /t:Rebuild /p:Configuration=Debug /p:Platform=x64
