name: C++ Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
        ./vcpkg/vcpkg install boost
        ./vcpkg/vcpkg install curl

    - name: Set up environment
      run: |
        echo "::set-env name=VCPKG_ROOT::${{ github.workspace }}/vcpkg"
        echo "::add-path::${{ github.workspace }}/vcpkg/installed/x64-linux/bin"

    - name: Build
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake
        cmake --build . --config Debug
